//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISA_TWAAOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fisiere
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public string FileType { get; set; }
        public Nullable<int> IdStudent { get; set; }
    
        public virtual Studenti Studenti { get; set; }
    }
}
