//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISA_TWAAOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Studenti()
        {
            this.Fisieres = new HashSet<Fisiere>();
        }
    
        public int Id { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string InitialaTatalui { get; set; }
        public string Email { get; set; }
        public Nullable<int> SpecializareId { get; set; }
        public string NivelStudii { get; set; }
        public string TitlulLucrarii { get; set; }
        public Nullable<int> ProfesorId { get; set; }
        public Nullable<int> LucrareId { get; set; }
        public string StadiuLucrare { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fisiere> Fisieres { get; set; }
        public virtual Profesori Profesori { get; set; }
        public virtual Specializari Specializari { get; set; }
    }
}
